# source https://github.com/victorhaggqvist/Pebble-TravisCI-Config
language: python

# 2.7 is the only verison officially supported
python:
  - "2.7"

script:
- pebble-dev/${PEBBLE_SDK}/bin/pebble build

before_install:
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk2/${PEBBLE_SDK}.tar.gz -O PebbleSDK.tar.gz
- wget http://assets.getpebble.com.s3-website-us-east-1.amazonaws.com/sdk/arm-cs-tools-ubuntu-universal.tar.gz
- mkdir pebble-dev
- tar -zxf PebbleSDK.tar.gz -C pebble-dev
- tar -zxf arm-cs-tools-ubuntu-universal.tar.gz -C pebble-dev/${PEBBLE_SDK}

# notice we don't create a virtualenv, travis to that be default already
install:
- pip install --upgrade pip # just to future proof, since travis seem to hang behind
- pip install --install-option="--no-cython-compile" cython
- "pip install -r pebble-dev/${PEBBLE_SDK}/requirements.txt"

env:
  global:
  - PEBBLE_SDK=PebbleSDK-3.6.2
